### ISSUE TITLE
Regression in v0.20.1 with DidYouMean changes in lib/thor/error.rb

### ISSUE THREAD

**Issue by bobziuchkovski** [erikhuda/thor#635]
The v0.20.1 `thor` release seems to have a regression in the `DidYouMean` changes introduced as part of https://github.com/erikhuda/thor/commit/3019cb518536118ef3a62e6c83250076193b4960

A simple reproducer is to install and run bundler-audit via docker on ruby 2.4:

```bash
$ docker run --rm -it ruby:2.4.5 bash -c "gem install bundler-audit --no-rdoc --no-ri && bundle-audit update"
Fetching: thor-0.20.1.gem (100%)
Successfully installed thor-0.20.1
Fetching: bundler-audit-0.6.0.gem (100%)
Successfully installed bundler-audit-0.6.0
2 gems installed
/usr/local/bundle/gems/thor-0.20.1/lib/thor/error.rb:12:in `<module:DidYouMean>': uninitialized constant Thor::DidYouMean::SpellChecker (NameError)
	from /usr/local/bundle/gems/thor-0.20.1/lib/thor/error.rb:6:in `<class:Thor>'
	from /usr/local/bundle/gems/thor-0.20.1/lib/thor/error.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/thor-0.20.1/lib/thor/base.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/thor-0.20.1/lib/thor.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/bundler-audit-0.6.0/lib/bundler/audit/cli.rb:21:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bundle/gems/bundler-audit-0.6.0/bin/bundle-audit:8:in `<top (required)>'
	from /usr/local/bundle/bin/bundle-audit:23:in `load'
	from /usr/local/bundle/bin/bundle-audit:23:in `<main>'
```

**Comment by cnemeth** [comment]
I get the same error on fresh install 

```
$ rails -v
Traceback (most recent call last):
	19: from /Users/cnemeth/.rbenv/versions/2.5.3/bin/rails:23:in `<main>'
	18: from /Users/cnemeth/.rbenv/versions/2.5.3/bin/rails:23:in `load'
	17: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.1/exe/rails:10:in `<top (required)>'
	16: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/cli.rb:12:in `<top (required)>'
	13: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:9:in `<top (required)>'
	10: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.1/lib/thor.rb:2:in `<top (required)>'
	 7: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.1/lib/thor/base.rb:4:in `<top (required)>'
	 4: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.1/lib/thor/error.rb:1:in `<top (required)>'
	 1: from /Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.1/lib/thor/error.rb:6:in `<class:Thor>'
/Users/cnemeth/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.1/lib/thor/error.rb:12:in `<module:DidYouMean>': uninitialized constant Thor::DidYouMean::SpellChecker (NameError)
```

### system setup (OSX Mojave)
```
$ rbenv -v
rbenv 1.1.1
$ gem -v
2.7.6
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
$ gem list | grep rails
rails (5.2.1)
```

**Comment by michaeldever** [comment]
I am seeing the same issue in version 0.20.1 on rails 5.2.1

**Comment by mmcgrath** [comment]
me too

**Comment by yatish27** [comment]
I see the same issue
